Sly 7 8
Punithshetty321/subscriberly pull request #1
Opened 2023-11-08 03:18 UTC by Punithshetty321

2023-11-08 04:00 UTC, pavankpdev requested changes

2023-11-08 04:00 UTC, pavankpdev commented on client/components/App.js
What is the purpose of this component?

2023-11-08 04:00 UTC, pavankpdev commented on client/components/App.js
> +                <a>Login</a>
The `<Link>` tag behind the scene is an anchor tag `<a>` no need to explicitly wrap it in a `<a>` again

2023-11-08 04:00 UTC, pavankpdev commented on client/pages/Login.jsx
> +      window.location.href = '';
use next router hook `useRouter`

2023-11-08 04:00 UTC, pavankpdev commented on client/pages/Login.jsx
> +    const response = await fetch('/api/User', {
Is the API setup? Was this tested? I don't see any API related config anywhere?
Where does `/api/User` redirect the request to? 

By the way use `axios` instead of `fetch` but do learn about both

2023-11-08 04:00 UTC, pavankpdev commented on client/pages/Register.jsx
> +    const response = await fetch('/api/Auth', {
Seems like the same API call here, test it before using it here, else this function will always fail with an exception

2023-11-08 04:00 UTC, pavankpdev commented on client/pages/Register.jsx
> +      window.location.href = '/login';
use next router hook `useRouter`

2023-11-08 04:04 UTC, pavankpdev commented
The frontend ui pages doesn't follow this route guidelines
![image](https://github.com/Punithshetty321/subscriberly/assets/52795191/4cab8f7f-239b-4c54-a403-f474ed0b40e3)

2023-11-29 05:40 UTC, Punithshetty321 commented on client/components/App.js
it is to toggle between login and register

2023-11-30 07:50 UTC, pavankpdev requested changes

2023-11-30 07:50 UTC, pavankpdev commented on client/auth/Login.jsx
file names should always be lowercase

2023-11-30 07:50 UTC, pavankpdev commented on client/auth/Login.jsx
> +        <label>
missing `htmlfor` attribute, violates accessibility

2023-11-30 07:50 UTC, pavankpdev commented on client/auth/Login.jsx
> +        <label>
missing `htmlfor` attribute, violates accessibility

2023-11-30 07:50 UTC, pavankpdev commented on client/auth/Login.jsx
> +      <style jsx>{`
Do not use this way to write styles, either write it in a separate files and import them as modules. Or use tailwind. 
Refer: [https://nextjs.org/docs/app/building-your-application/styling/css-modules](https://nextjs.org/docs/app/building-your-application/styling/css-modules)

2023-11-30 07:50 UTC, pavankpdev commented on client/auth/Login.jsx
> +  const handleLogin = () => {
Missing validation for email and password, within the handleLogin method. 

The function should handle the following case
1. missing email and password case
2. email format
3. password min length

2023-11-30 07:50 UTC, pavankpdev commented on client/auth/Register.jsx
file names should always be lowercase

2023-11-30 07:50 UTC, pavankpdev commented on client/auth/Register.jsx
> +  const handleRegister = () => {
Missing validation for email and password, within the handleLogin method. 

The function should handle the following case
1. missing email and password case
2. email format
3. password min length

2023-11-30 07:50 UTC, pavankpdev commented on client/auth/Register.jsx
> +        <label>
missing `htmlfor` attribute, violates accessibility

2023-11-30 07:50 UTC, pavankpdev commented on client/auth/Register.jsx
> +        <label>
missing `htmlfor` attribute, violates accessibility

2023-11-30 07:50 UTC, pavankpdev commented on client/auth/Register.jsx
> +        <br />
Do not use `<br />` use flex column and provide gap

Refer: Flexbox in css

2023-12-03 01:54 UTC, merged