CRUD Api for products
Punithshetty321/subscriberly pull request #3
Opened 2023-11-30 16:36 UTC by Shyam-crypto

2023-12-08 06:40 UTC, pavankpdev requested changes
Create a single bruno file, and maintain all the request record inside that, please modify it

2023-12-08 06:40 UTC, pavankpdev commented on server/models/product.js
> +    default: () => uuidv4(), // You need to import the uuidv4 function
This can be simplified with just `default: uuidv4`.
Also remove the comment

2023-12-11 05:02 UTC, pavankpdev approved these changes
1. Update `.example.env` with all the new ENVs created, keep it up to date in the future as well. 
2. Fix the issues reported

2023-12-11 05:02 UTC, pavankpdev commented on server/routes/product.js
Seems like input validation was skipped, I tried to provide incorrect types for the value, for example, I used a number for the properties that were suppose to be string and the API returned success status

![image](https://github.com/Punithshetty321/subscriberly/assets/52795191/763e20b7-2110-4a04-820d-6db3ebcf1aec)

This should be fixed.

2023-12-12 14:27 UTC, pavankpdev requested changes
Add input validations to API. This is a mandatory step, every single data that the API needs as an input should be validated.

2023-12-16 13:27 UTC, pavan38kp reviewed
@Shyam-crypto Seems better now, I'll run it from my end before approving the PR

2023-12-16 13:28 UTC, pavankpdev reviewed
Looks good, I'll test it form my end once, before approving

2023-12-16 13:31 UTC, Shyam-crypto commented
Okay👍

2023-12-19 17:35 UTC, pavankpdev commented
Hey, @Shyam-crypto seems like there's a bug, I've been stuck here, no matter what type data I pass, I get the same response. 

Request
`POST /api/products/products`

![image](https://github.com/Punithshetty321/subscriberly/assets/52795191/fccac337-ca42-4a06-8c74-d5c0d59e5227)

2023-12-19 17:37 UTC, pavankpdev commented
Request 
`PUT /api/products/update/:id`

![Uploading image.png…]()

2023-12-19 17:40 UTC, pavankpdev commented
One more thing, the `getAllProducts` and `getProductByID` are private routes why? 
I said that manually check for the access token in the headers, if exist show the edit mode else return only read mode. 

How can we expect users to get the product, if it's private

2023-12-19 17:48 UTC, Shyam-crypto commented
Okay i will correct it.

2023-12-21 07:35 UTC, pavankpdev commented
@Shyam-crypto about the other two issues 

1: https://github.com/Punithshetty321/subscriberly/pull/3#issuecomment-1863217240
2: https://github.com/Punithshetty321/subscriberly/pull/3#issuecomment-1863210489

2023-12-29 07:47 UTC, Shyam-crypto commented
@pavankpdev updated the getProductById and corrected the error from interval.

2024-01-02 13:50 UTC, pavankpdev commented on server/controller/product.js
> +    if (token) {
noice

2024-01-02 13:51 UTC, pavankpdev reviewed
Looks good, I'll test the updates before merging, hope bruno files are updated

2024-01-02 13:58 UTC, pavankpdev commented
Everything looks good, merging the PR

2024-01-02 13:58 UTC, merged