Auth login
Punithshetty321/subscriberly pull request #4
Opened 2023-12-11 04:39 UTC by Punithshetty321

2023-12-12 14:30 UTC, pavankpdev requested changes

2023-12-12 14:30 UTC, pavankpdev commented on client/configs/axios.js
> +    baseURL: 'http://localhost:4000'
use environment variables to specify the base URL, [refer this doc](https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables)

2023-12-12 14:30 UTC, pavankpdev commented on client/package.json
> +    "cors": "^2.8.5",
remove this package, `cors` is not required for frontend

2023-12-12 14:30 UTC, pavankpdev commented on server/routes/auth.js
> +import { registerUser, loginUser, } from '../controller/Auth.js';
Was this filename change verified? 
If not do it by running the server

2023-12-16 07:10 UTC, pavankpdev requested changes
Need the confirmation on the testing status for the new ENV change

2023-12-16 07:10 UTC, pavankpdev commented on client/configs/axios.js
> +    baseURL: process.env.BASE_URL,
Was this tested?

2023-12-16 07:10 UTC, pavankpdev commented on client/package.json
> +    "dotenv": "^16.3.1",
dotenv is not required, NextJS as support for ENVs by default

2023-12-18 15:56 UTC, Punithshetty321 commented on client/configs/axios.js
> +    baseURL: process.env.BASE_URL,
yes its working

2023-12-19 17:41 UTC, pavankpdev approved these changes
looks good

2023-12-19 17:41 UTC, merged